/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import Models.AddressModel;
import Models.CashFilterDocument;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author caiol
 */
public class ViewportPayments extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportPayments.class.getName());

    private double totalPrice = 0.0, initialTotalPrice = 0.0;
    private double totalPaid = 0.0, totalInCash = 0.0; 
    private final double minimumInstallmentsValue = 30.00;
    
    // SALE DATA:
    public String client_name;
    public String client_cpf;
    public String date;
    public DefaultTableModel cart;

    /**
     * Creates new form ViewportPagamentos
     * @param totalPrice
     * @param client_name
     * @param client_cpf
     * @param date
     * @param cart
     */
    public ViewportPayments(
            double totalPrice,
            String client_name,
            String client_cpf,
            String date,
            DefaultTableModel cart
        ) 
    {
        initComponents();
        this.client_name = client_name;
        this.client_cpf = client_cpf;
        this.date = date;
        this.cart = cart;
        
        for (int i = 0; i < this.cart.getRowCount(); i++){
            this.totalPrice += Double.parseDouble( this.cart.getValueAt(i, 4).toString() );
        }
        
        ((AbstractDocument) TXTDinheiro.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTDebito.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTPIX.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTCredito.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTLink.getDocument()).setDocumentFilter(new CashFilterDocument());
    }

    private ArrayList<String> CalculateInstallments() {
        ArrayList<String> plots = new ArrayList<>();

        for (int i = 1; i <= 12; i++) {
            if (Double.parseDouble(TXTCredito.getText().replace(",", ".")) / i >= minimumInstallmentsValue) {
                plots.add(i + "x");
            } else {
                if (plots.isEmpty()) {
                    plots.add("1x");
                }
                break;
            }
        }

        return plots;
    }

    private void UpdateCBParcelas() {
        ArrayList<String> installmentsList = new ArrayList<>();

        DefaultComboBoxModel model = (DefaultComboBoxModel) CBParcelas.getModel();
        model.removeAllElements();
        
        if (!TXTCredito.getText().isBlank()) {
            if (Double.parseDouble(TXTCredito.getText()) > 0) {
                installmentsList = CalculateInstallments();
            }
            else {
                installmentsList.add("1x");
            }
        }
        else {
            installmentsList.add("1x");
        }

        for (String plot : installmentsList) {
            model.addElement(plot);
        }
    }
    
    private void UpdateSelectedIndex(int nextSelectedIndex){
        int previousSelectedIndex = TABBEDPANEMain.getSelectedIndex();
        TABBEDPANEMain.setSelectedIndex(nextSelectedIndex);
        
        TABBEDPANEMain.setEnabledAt(previousSelectedIndex, false);
        TABBEDPANEMain.setBackgroundAt(previousSelectedIndex, new Color(204, 204, 204));
        
        TABBEDPANEMain.setEnabledAt(nextSelectedIndex, true);
        TABBEDPANEMain.setBackgroundAt(nextSelectedIndex, new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LABELTotalVenda = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TABBEDPANEMain = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        BTNCancelarDinheiro = new javax.swing.JButton();
        BTNConfirmarDinheiro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTDinheiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LABELAPagar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TXTDebito = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TXTPIX = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TXTLink = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TXTCredito = new javax.swing.JTextField();
        CBParcelas = new javax.swing.JComboBox<>();
        CHECKDesconto = new javax.swing.JCheckBox();
        TBDinheiro = new javax.swing.JToggleButton();
        TBDebito = new javax.swing.JToggleButton();
        TBPix = new javax.swing.JToggleButton();
        TBLink = new javax.swing.JToggleButton();
        TBCredito = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TXTCEP = new javax.swing.JTextField();
        TXTEndereco = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TXTTelefone = new javax.swing.JTextField();
        BUTTONPreencher = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        TXTNumero = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TXTReferencia = new javax.swing.JTextField();
        BTNConfirmarFinalizar = new javax.swing.JButton();
        BTNCancelarFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));

        jPanel2.setBackground(new java.awt.Color(149, 117, 47));

        LABELTotalVenda.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalVenda.setForeground(new java.awt.Color(0, 0, 0));
        LABELTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalVenda.setText("0.00");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("TOTAL DA VENDA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalVenda)
                .addContainerGap())
        );

        TABBEDPANEMain.setBackground(new java.awt.Color(255, 255, 255));
        TABBEDPANEMain.setForeground(new java.awt.Color(0, 0, 0));
        TABBEDPANEMain.setEnabled(false);
        TABBEDPANEMain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BTNCancelarDinheiro.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarDinheiro.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarDinheiro.setText("CANCELAR");
        BTNCancelarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarDinheiroActionPerformed(evt);
            }
        });

        BTNConfirmarDinheiro.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarDinheiro.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarDinheiro.setText("CONFIRMAR");
        BTNConfirmarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarDinheiroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dinheiro:");

        TXTDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        TXTDinheiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTDinheiro.setForeground(new java.awt.Color(0, 0, 0));
        TXTDinheiro.setText("0.00");
        TXTDinheiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTDinheiroKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL A PAGAR:");

        LABELAPagar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELAPagar.setForeground(new java.awt.Color(204, 0, 0));
        LABELAPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELAPagar.setText("0.00");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Débito:");

        TXTDebito.setBackground(new java.awt.Color(255, 255, 255));
        TXTDebito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTDebito.setForeground(new java.awt.Color(0, 0, 0));
        TXTDebito.setText("0.00");
        TXTDebito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTDebitoKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("PIX:");

        TXTPIX.setBackground(new java.awt.Color(255, 255, 255));
        TXTPIX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTPIX.setForeground(new java.awt.Color(0, 0, 0));
        TXTPIX.setText("0.00");
        TXTPIX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTPIX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTPIXKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Link de pgt.:");

        TXTLink.setBackground(new java.awt.Color(255, 255, 255));
        TXTLink.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTLink.setForeground(new java.awt.Color(0, 0, 0));
        TXTLink.setText("0.00");
        TXTLink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTLink.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTLinkKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Crédito:");

        TXTCredito.setBackground(new java.awt.Color(255, 255, 255));
        TXTCredito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTCredito.setForeground(new java.awt.Color(0, 0, 0));
        TXTCredito.setText("0.00");
        TXTCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTCreditoKeyReleased(evt);
            }
        });

        CBParcelas.setBackground(new java.awt.Color(255, 255, 255));
        CBParcelas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBParcelas.setForeground(new java.awt.Color(0, 0, 0));
        CBParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x", "2x", "3x", "4x", "5x", "6x", "7x", "8x", "9x", "10x", "11x", "12x" }));
        CBParcelas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CBParcelasPropertyChange(evt);
            }
        });

        CHECKDesconto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CHECKDesconto.setForeground(new java.awt.Color(102, 102, 102));
        CHECKDesconto.setText("Desconto de 5% (Pix e Dinheiro)");
        CHECKDesconto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CHECKDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKDescontoActionPerformed(evt);
            }
        });

        TBDinheiro.setBackground(new java.awt.Color(192, 179, 166));
        TBDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TBDinheiro.setForeground(new java.awt.Color(0, 0, 0));
        TBDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkbox.png"))); // NOI18N
        TBDinheiro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TBDinheiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TBDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBDinheiroActionPerformed(evt);
            }
        });

        TBDebito.setBackground(new java.awt.Color(192, 179, 166));
        TBDebito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TBDebito.setForeground(new java.awt.Color(0, 0, 0));
        TBDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkbox.png"))); // NOI18N
        TBDebito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TBDebito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TBPix.setBackground(new java.awt.Color(192, 179, 166));
        TBPix.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TBPix.setForeground(new java.awt.Color(0, 0, 0));
        TBPix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkbox.png"))); // NOI18N
        TBPix.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TBPix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TBLink.setBackground(new java.awt.Color(192, 179, 166));
        TBLink.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TBLink.setForeground(new java.awt.Color(0, 0, 0));
        TBLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkbox.png"))); // NOI18N
        TBLink.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TBLink.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TBCredito.setBackground(new java.awt.Color(192, 179, 166));
        TBCredito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TBCredito.setForeground(new java.awt.Color(0, 0, 0));
        TBCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkbox.png"))); // NOI18N
        TBCredito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TBCredito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELAPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BTNConfirmarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(BTNCancelarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTLink, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TBLink))
                            .addComponent(CHECKDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(TXTPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TBPix)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(38, 38, 38)
                                .addComponent(TXTDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TBDebito)
                                .addGap(100, 100, 100))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(TXTDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TBDinheiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBParcelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTCredito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TBCredito)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELAPagar)
                .addGap(18, 18, 18)
                .addComponent(CHECKDesconto)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TBDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXTCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(TBCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CBParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TXTDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TBDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TXTDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TBPix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXTLink, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TBLink, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BTNConfirmarDinheiro, jLabel1});

        TABBEDPANEMain.addTab("Métodos de Pagamento", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaminhaoPreto.png"))); // NOI18N
        jLabel26.setText("(Opcional) Endereço para entrega");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("CEP:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Endereço:");

        TXTCEP.setBackground(new java.awt.Color(255, 255, 255));
        TXTCEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTCEP.setForeground(new java.awt.Color(0, 0, 0));
        TXTCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TXTEndereco.setBackground(new java.awt.Color(255, 255, 255));
        TXTEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTEndereco.setForeground(new java.awt.Color(0, 0, 0));
        TXTEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Telefone para Contato:");

        TXTTelefone.setBackground(new java.awt.Color(255, 255, 255));
        TXTTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTTelefone.setForeground(new java.awt.Color(0, 0, 0));
        TXTTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BUTTONPreencher.setBackground(new java.awt.Color(192, 179, 166));
        BUTTONPreencher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTONPreencher.setForeground(new java.awt.Color(0, 0, 102));
        BUTTONPreencher.setText("Preencher");
        BUTTONPreencher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONPreencherActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Número:");

        TXTNumero.setBackground(new java.awt.Color(255, 255, 255));
        TXTNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTNumero.setForeground(new java.awt.Color(0, 0, 0));
        TXTNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Referência:");

        TXTReferencia.setBackground(new java.awt.Color(255, 255, 255));
        TXTReferencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTReferencia.setForeground(new java.awt.Color(0, 0, 0));
        TXTReferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTEndereco)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(TXTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BUTTONPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(TXTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(TXTTelefone))))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BTNConfirmarFinalizar.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarFinalizar.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarFinalizar.setText("CONFIRMAR");
        BTNConfirmarFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarFinalizarActionPerformed(evt);
            }
        });

        BTNCancelarFinalizar.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarFinalizar.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarFinalizar.setText("CANCELAR");
        BTNCancelarFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(BTNConfirmarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNCancelarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TABBEDPANEMain.addTab("FINALIZAR", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TABBEDPANEMain)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TABBEDPANEMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        LABELTotalVenda.setText(String.valueOf(this.totalPrice));
        
        LABELAPagar.setText(String.valueOf(this.totalPrice));
        
        UpdateSelectedIndex(0);
    }//GEN-LAST:event_formWindowActivated

    private void BUTTONPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONPreencherActionPerformed
        AddressModel c = new AddressModel();
        ViewportsUtils utils = new ViewportsUtils();

        c = utils.fillAddressByCep(TXTCEP.getText());

        TXTEndereco.setText(c.getAddress());
    }//GEN-LAST:event_BUTTONPreencherActionPerformed

    private void BTNConfirmarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarDinheiroActionPerformed
        if(totalPrice - totalPaid > 0){       
            UpdateSelectedIndex(1);
        }
        else{
            UpdateSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Não pagou todo o valor da compra!");
        }
    }//GEN-LAST:event_BTNConfirmarDinheiroActionPerformed

    private void BTNCancelarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarDinheiroActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarDinheiroActionPerformed

    private void BTNConfirmarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarFinalizarActionPerformed
        if (totalPaid >= totalPrice){
            double totalPrice = this.totalPrice;
            double totalPaid = this.totalPaid;
            double totalInCash = this.totalInCash;
            boolean isDiscount = CHECKDesconto.isSelected();
            String client_name = this.client_name;
            String client_cpf = this.client_cpf;
            String date = this.date;
            double cash = Double.parseDouble(TXTDinheiro.getText());
            double debit = Double.parseDouble(TXTDebito.getText());
            double pix = Double.parseDouble(TXTPIX.getText());
            double link = Double.parseDouble(TXTLink.getText());
            double credit = Double.parseDouble(TXTCredito.getText());
            int installments = CBParcelas.getSelectedIndex() + 1;
            String client_address = TXTEndereco.getText() + ", " + TXTNumero.getText() + ", " + TXTCEP.getText();
            String client_address_ref = TXTReferencia.getText();
            DefaultTableModel cart = this.cart;
            
            ViewportConfirmSale viewCS = new ViewportConfirmSale(totalPrice, totalPaid, totalInCash, isDiscount, client_name, client_cpf, date, cash, debit, pix, link, credit, installments, client_address, client_address_ref, cart);

            viewCS.setVisible(true);
        }
        else{
            totalPaid = 0;
            totalInCash = 0;
            JOptionPane.showMessageDialog(null, "Não pagou todo o valor da compra!");
            UpdateSelectedIndex(0);
        }
    }//GEN-LAST:event_BTNConfirmarFinalizarActionPerformed

    private void BTNCancelarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarFinalizarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarFinalizarActionPerformed

    private void CBParcelasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CBParcelasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_CBParcelasPropertyChange

    private void CHECKDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHECKDescontoActionPerformed

    private void TXTDebitoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDebitoKeyReleased
        UpdateTotals();
    }//GEN-LAST:event_TXTDebitoKeyReleased

    private void TXTPIXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPIXKeyReleased
        UpdateTotals();
    }//GEN-LAST:event_TXTPIXKeyReleased

    private void TXTLinkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTLinkKeyReleased
        UpdateTotals();
    }//GEN-LAST:event_TXTLinkKeyReleased

    private void TXTCreditoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCreditoKeyReleased
        UpdateTotals();
    }//GEN-LAST:event_TXTCreditoKeyReleased

    private void TXTDinheiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDinheiroKeyReleased
        UpdateTotals();
    }//GEN-LAST:event_TXTDinheiroKeyReleased

    private void TBDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBDinheiroActionPerformed

    private void UpdateTotals(){
        double dinheiro = Double.parseDouble( TXTDinheiro.getText() );
        double debito = Double.parseDouble( TXTDebito.getText() );
        double pix = Double.parseDouble( TXTPIX.getText() );
        double link = Double.parseDouble( TXTLink.getText() );
        double credito = Double.parseDouble( TXTCredito.getText() );
        
        this.totalPaid = dinheiro + debito + pix + link + credito;
        
        double remainsToPay = this.totalPrice - this.totalPaid;
        
        LABELAPagar.setText( String.valueOf( remainsToPay ) );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Ninbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ViewportPayments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancelarDinheiro;
    private javax.swing.JButton BTNCancelarFinalizar;
    private javax.swing.JButton BTNConfirmarDinheiro;
    private javax.swing.JButton BTNConfirmarFinalizar;
    private javax.swing.JButton BUTTONPreencher;
    private javax.swing.JComboBox<String> CBParcelas;
    private javax.swing.JCheckBox CHECKDesconto;
    private javax.swing.JLabel LABELAPagar;
    private javax.swing.JLabel LABELTotalVenda;
    private javax.swing.JTabbedPane TABBEDPANEMain;
    private javax.swing.JToggleButton TBCredito;
    private javax.swing.JToggleButton TBDebito;
    private javax.swing.JToggleButton TBDinheiro;
    private javax.swing.JToggleButton TBLink;
    private javax.swing.JToggleButton TBPix;
    private javax.swing.JTextField TXTCEP;
    private javax.swing.JTextField TXTCredito;
    private javax.swing.JTextField TXTDebito;
    private javax.swing.JTextField TXTDinheiro;
    private javax.swing.JTextField TXTEndereco;
    private javax.swing.JTextField TXTLink;
    private javax.swing.JTextField TXTNumero;
    private javax.swing.JTextField TXTPIX;
    private javax.swing.JTextField TXTReferencia;
    private javax.swing.JTextField TXTTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
