/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import DAOs.ClientsDAO;
import Models.ClientsModel;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caiol
 */
public class ViewportClients extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportClients.class.getName());

    /**
     * Creates new form ViewportMainMenu
     */
    public ViewportClients() {
        initComponents();
    }

    private void listTable() {
        ClientsDAO dao = new ClientsDAO();
        List<ClientsModel> list = dao.listClients();

        DefaultTableModel tableData = (DefaultTableModel) TableListClients.getModel();
        tableData.setNumRows(0);

        for (ClientsModel c : list) {
            tableData.addRow(new Object[]{
                c.getId(),
                c.getName(),
                c.getCPF(),
                c.getCellphone(),
                c.getEmail(),
                c.getCEP(),
                c.getAddress()
            });
        }
    }

    private void SearchAddress(String CEP) {
        ClientsModel c = new ClientsModel();
        ViewportsUtils utils = new ViewportsUtils();

        c = utils.fillAddressByCep(CEP);

        TXTEndereco.setText(c.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        ClientDataJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTCEP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXTCPF = new javax.swing.JTextField();
        PesquisarButton = new javax.swing.JButton();
        PesquisarButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ConsultJPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TXTFiltrarCPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListClients = new javax.swing.JTable();
        EDITARButton = new javax.swing.JButton();
        EXCLUIRButton = new javax.swing.JButton();
        NOVOButton = new javax.swing.JButton();

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));
        jPanel1.setForeground(new java.awt.Color(192, 179, 166));

        jPanel2.setBackground(new java.awt.Color(149, 117, 47));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        MainTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        MainTabbedPane.setForeground(new java.awt.Color(0, 0, 0));

        ClientDataJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ClientDataJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClientDataJPanel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código:");

        TXTCodigo.setEditable(false);
        TXTCodigo.setBackground(new java.awt.Color(204, 204, 204));
        TXTCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCodigo.setForeground(new java.awt.Color(0, 0, 0));
        TXTCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCodigo.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        TXTNome.setBackground(new java.awt.Color(255, 255, 255));
        TXTNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTNome.setForeground(new java.awt.Color(0, 0, 0));
        TXTNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("E-mail:");

        TXTEmail.setBackground(new java.awt.Color(255, 255, 255));
        TXTEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTEmail.setForeground(new java.awt.Color(0, 0, 0));
        TXTEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEmailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Celular:");

        TXTCelular.setBackground(new java.awt.Color(255, 255, 255));
        TXTCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCelular.setForeground(new java.awt.Color(0, 0, 0));
        TXTCelular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CEP:");

        TXTCEP.setBackground(new java.awt.Color(255, 255, 255));
        TXTCEP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCEP.setForeground(new java.awt.Color(0, 0, 0));
        TXTCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCEPActionPerformed(evt);
            }
        });
        TXTCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTCEPKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Endereço:");

        TXTEndereco.setBackground(new java.awt.Color(255, 255, 255));
        TXTEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTEndereco.setForeground(new java.awt.Color(0, 0, 0));
        TXTEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CPF:");

        TXTCPF.setBackground(new java.awt.Color(255, 255, 255));
        TXTCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCPF.setForeground(new java.awt.Color(0, 0, 0));
        TXTCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PesquisarButton.setBackground(new java.awt.Color(192, 179, 166));
        PesquisarButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        PesquisarButton.setForeground(new java.awt.Color(0, 0, 0));
        PesquisarButton.setText("Pesquisar");
        PesquisarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarButtonActionPerformed(evt);
            }
        });

        PesquisarButton1.setBackground(new java.awt.Color(192, 179, 166));
        PesquisarButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PesquisarButton1.setForeground(new java.awt.Color(0, 0, 102));
        PesquisarButton1.setText("Preencher");
        PesquisarButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PesquisarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("*Insira o número da casa dentro de Endereço*");

        javax.swing.GroupLayout ClientDataJPanelLayout = new javax.swing.GroupLayout(ClientDataJPanel);
        ClientDataJPanel.setLayout(ClientDataJPanelLayout);
        ClientDataJPanelLayout.setHorizontalGroup(
            ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientDataJPanelLayout.createSequentialGroup()
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientDataJPanelLayout.createSequentialGroup()
                                                .addComponent(TXTNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TXTCelular)
                                            .addComponent(TXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientDataJPanelLayout.createSequentialGroup()
                                        .addComponent(TXTCEP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PesquisarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(48, 48, 48))))
        );
        ClientDataJPanelLayout.setVerticalGroup(
            ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                .addComponent(PesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TXTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        ClientDataJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PesquisarButton, PesquisarButton1});

        MainTabbedPane.addTab("Dados Pessoais", ClientDataJPanel);

        ConsultJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ConsultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CPF:");

        TXTFiltrarCPF.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarCPF.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarCPFKeyPressed(evt);
            }
        });

        TableListClients.setBackground(new java.awt.Color(233, 220, 205));
        TableListClients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableListClients.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableListClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "Celular", "E-mail", "CEP", "Endereço"
            }
        ));
        TableListClients.setGridColor(new java.awt.Color(255, 255, 255));
        TableListClients.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TableListClients.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TableListClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableListClients);

        javax.swing.GroupLayout ConsultJPanelLayout = new javax.swing.GroupLayout(ConsultJPanel);
        ConsultJPanel.setLayout(ConsultJPanelLayout);
        ConsultJPanelLayout.setHorizontalGroup(
            ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(ConsultJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTFiltrarCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addGap(627, 627, 627))))
        );
        ConsultJPanelLayout.setVerticalGroup(
            ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXTFiltrarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Consultar", ConsultJPanel);

        EDITARButton.setBackground(new java.awt.Color(255, 255, 255));
        EDITARButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EDITARButton.setForeground(new java.awt.Color(0, 0, 0));
        EDITARButton.setText("EDITAR");
        EDITARButton.setToolTipText("");
        EDITARButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EDITARButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARButtonActionPerformed(evt);
            }
        });

        EXCLUIRButton.setBackground(new java.awt.Color(255, 255, 255));
        EXCLUIRButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EXCLUIRButton.setForeground(new java.awt.Color(0, 0, 0));
        EXCLUIRButton.setText("EXCLUIR");
        EXCLUIRButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EXCLUIRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIRButtonActionPerformed(evt);
            }
        });

        NOVOButton.setBackground(new java.awt.Color(255, 255, 255));
        NOVOButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NOVOButton.setForeground(new java.awt.Color(0, 0, 0));
        NOVOButton.setText("NOVO");
        NOVOButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NOVOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOVOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainTabbedPane)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NOVOButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EDITARButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EXCLUIRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDITARButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXCLUIRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOVOButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEmailActionPerformed

    private void TXTCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCEPActionPerformed

    private void TXTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNomeActionPerformed

    private void EDITARButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARButtonActionPerformed
        if (TXTNome.getText() != null && TXTCPF.getText() != null) {
            try {
                ClientsModel currentClient = new ClientsModel();

                currentClient.setId(Integer.parseInt(TXTCodigo.getText()));
                currentClient.setName(TXTNome.getText());
                currentClient.setCPF(TXTCPF.getText());
                currentClient.setCEP(TXTCEP.getText());
                currentClient.setAddress(TXTEndereco.getText());
                currentClient.setCellphone(TXTCelular.getText());
                currentClient.setEmail(TXTEmail.getText());

                ClientsDAO dao = new ClientsDAO();

                dao.updateClient(currentClient);

            } catch (Exception e) {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Nome e/ou um CPF válidos.");
        }
    }//GEN-LAST:event_EDITARButtonActionPerformed

    private void EXCLUIRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIRButtonActionPerformed
        if (TXTNome.getText() != null && TXTCPF.getText() != null) {
            try {
                ClientsModel currentClient = new ClientsModel();

                currentClient.setId(Integer.parseInt(TXTCodigo.getText()));

                ClientsDAO dao = new ClientsDAO();

                dao.deleteClient(currentClient);

                new ViewportsUtils().clearPanel(ClientDataJPanel);
            } catch (Exception e) {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Nome e/ou um CPF válidos.");
        }
    }//GEN-LAST:event_EXCLUIRButtonActionPerformed

    private void NOVOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOVOButtonActionPerformed
        if (TXTNome.getText() != null && TXTCPF.getText() != null) {
            try {
                ClientsModel currentClient = new ClientsModel();

                currentClient.setName(TXTNome.getText());
                currentClient.setCPF(TXTCPF.getText());
                currentClient.setCEP(TXTCEP.getText());
                currentClient.setAddress(TXTEndereco.getText());
                currentClient.setCellphone(TXTCelular.getText());
                currentClient.setEmail(TXTEmail.getText());

                ClientsDAO dao = new ClientsDAO();

                dao.registerClient(currentClient);

                new ViewportsUtils().clearPanel(ClientDataJPanel);
            } catch (Exception e) {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Nome e/ou um CPF válidos.");
        }
    }//GEN-LAST:event_NOVOButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTable();
    }//GEN-LAST:event_formWindowActivated

    private void TableListClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListClientsMouseClicked
        TXTCodigo.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 0).toString());
        TXTNome.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 1).toString());
        TXTCPF.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 2).toString());
        TXTCelular.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 3).toString());
        TXTEmail.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 4).toString());
        TXTCEP.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 5).toString());
        TXTEndereco.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 6).toString());

        MainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_TableListClientsMouseClicked

    private void TXTFiltrarCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarCPFKeyPressed
        String clientCPF = "%" + TXTFiltrarCPF.getText() + "%";

        ClientsDAO dao = new ClientsDAO();
        List<ClientsModel> list = dao.searchClientsByName(clientCPF);

        DefaultTableModel tableData = (DefaultTableModel) TableListClients.getModel();
        tableData.setNumRows(0);

        for (ClientsModel c : list) {
            tableData.addRow(new Object[]{
                c.getId(),
                c.getName(),
                c.getCPF(),
                c.getCellphone(),
                c.getEmail(),
                c.getCEP(),
                c.getAddress()
            });
        }
    }//GEN-LAST:event_TXTFiltrarCPFKeyPressed

    private void PesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarButtonActionPerformed
        String clientName = TXTNome.getText();
        ClientsModel client = new ClientsModel();
        ClientsDAO dao = new ClientsDAO();

        client = dao.consultClientByName(clientName);

        if (client.getName() != null) {
            TXTCodigo.setText(String.valueOf(client.getId()));
            TXTNome.setText(client.getName());
            TXTCPF.setText(client.getCPF());
            TXTCelular.setText(client.getCellphone());
            TXTEmail.setText(client.getEmail());
            TXTCEP.setText(client.getCEP());
            TXTEndereco.setText(client.getAddress());
        } else {
            JOptionPane.showMessageDialog(null, "FALHA ao ENCONTRAR Cliente de nome: " + clientName);
        }
    }//GEN-LAST:event_PesquisarButtonActionPerformed

    private void PesquisarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarButton1ActionPerformed
        SearchAddress(TXTCEP.getText());
    }//GEN-LAST:event_PesquisarButton1ActionPerformed

    private void TXTCEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCEPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SearchAddress(TXTCEP.getText());
        }
    }//GEN-LAST:event_TXTCEPKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewportClients().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientDataJPanel;
    private javax.swing.JPanel ConsultJPanel;
    private javax.swing.JButton EDITARButton;
    private javax.swing.JButton EXCLUIRButton;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton NOVOButton;
    private javax.swing.JButton PesquisarButton;
    private javax.swing.JButton PesquisarButton1;
    private javax.swing.JTextField TXTCEP;
    private javax.swing.JTextField TXTCPF;
    private javax.swing.JTextField TXTCelular;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JTextField TXTEmail;
    private javax.swing.JTextField TXTEndereco;
    private javax.swing.JTextField TXTFiltrarCPF;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JTable TableListClients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
