/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import Models.EmployeesModel;
import javax.swing.JOptionPane;

/**
 *
 * @author caiol
 */
public class ViewportMainMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportMainMenu.class.getName());
    private EmployeesModel employeeLogged;

    /**
     * Creates new form ViewportMainMenu
     */
    public ViewportMainMenu(EmployeesModel employeeLogged) {
        initComponents();

        this.employeeLogged = employeeLogged;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BUTTONVendas = new javax.swing.JButton();
        BUTTONFuncionarios = new javax.swing.JButton();
        BUTTONEstoque = new javax.swing.JButton();
        BUTTONClientes = new javax.swing.JButton();
        BUTTONSair = new javax.swing.JButton();
        LABELNome = new javax.swing.JLabel();
        BUTTONDespesas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));

        jPanel2.setBackground(new java.awt.Color(149, 117, 47));

        BUTTONVendas.setBackground(new java.awt.Color(255, 255, 255));
        BUTTONVendas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BUTTONVendas.setForeground(new java.awt.Color(255, 255, 255));
        BUTTONVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CarrinhoWhite_Cheio.png"))); // NOI18N
        BUTTONVendas.setText("Vendas");
        BUTTONVendas.setBorder(null);
        BUTTONVendas.setContentAreaFilled(false);
        BUTTONVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONVendasActionPerformed(evt);
            }
        });

        BUTTONFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        BUTTONFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BUTTONFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        BUTTONFuncionarios.setText("Funcionários");
        BUTTONFuncionarios.setBorder(null);
        BUTTONFuncionarios.setContentAreaFilled(false);
        BUTTONFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONFuncionariosActionPerformed(evt);
            }
        });

        BUTTONEstoque.setBackground(new java.awt.Color(255, 255, 255));
        BUTTONEstoque.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BUTTONEstoque.setForeground(new java.awt.Color(255, 255, 255));
        BUTTONEstoque.setText("Estoque");
        BUTTONEstoque.setBorder(null);
        BUTTONEstoque.setContentAreaFilled(false);
        BUTTONEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONEstoqueActionPerformed(evt);
            }
        });

        BUTTONClientes.setBackground(new java.awt.Color(255, 255, 255));
        BUTTONClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BUTTONClientes.setForeground(new java.awt.Color(255, 255, 255));
        BUTTONClientes.setText("Clientes");
        BUTTONClientes.setBorder(null);
        BUTTONClientes.setContentAreaFilled(false);
        BUTTONClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONClientesActionPerformed(evt);
            }
        });

        BUTTONSair.setBackground(new java.awt.Color(255, 255, 255));
        BUTTONSair.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BUTTONSair.setForeground(new java.awt.Color(255, 255, 255));
        BUTTONSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sair.png"))); // NOI18N
        BUTTONSair.setBorder(null);
        BUTTONSair.setContentAreaFilled(false);
        BUTTONSair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BUTTONSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONSairActionPerformed(evt);
            }
        });

        LABELNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LABELNome.setForeground(new java.awt.Color(255, 255, 255));
        LABELNome.setText("NOME");

        BUTTONDespesas.setBackground(new java.awt.Color(255, 255, 255));
        BUTTONDespesas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BUTTONDespesas.setForeground(new java.awt.Color(255, 255, 255));
        BUTTONDespesas.setText("Despesas");
        BUTTONDespesas.setBorder(null);
        BUTTONDespesas.setContentAreaFilled(false);
        BUTTONDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONDespesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTTONVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTTONFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(BUTTONEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTTONClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BUTTONSair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LABELNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BUTTONDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUTTONVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BUTTONFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTONEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTONClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTONDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTTONSair, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(LABELNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 465, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTONVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONVendasActionPerformed
        ViewportSales viewportSales = new ViewportSales(this.employeeLogged);
        viewportSales.setVisible(true);
    }//GEN-LAST:event_BUTTONVendasActionPerformed

    private void BUTTONFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONFuncionariosActionPerformed
        if (this.employeeLogged.getAcessLevel().equals("Administrador")) {
            ViewportEmployees viewportEmployees = new ViewportEmployees();
            viewportEmployees.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não possui Acesso...");
        }
    }//GEN-LAST:event_BUTTONFuncionariosActionPerformed

    private void BUTTONEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONEstoqueActionPerformed
        ViewportStock viewportStock = new ViewportStock(this.employeeLogged);
        viewportStock.setVisible(true);
    }//GEN-LAST:event_BUTTONEstoqueActionPerformed

    private void BUTTONSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Isso fechará TODAS as janelas abertas!", "SAIR ?", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            for (java.awt.Window window : java.awt.Window.getWindows()) {
                if (window instanceof javax.swing.JFrame) {
                    window.dispose();
                }
            }

            ViewportLogin viewportLogin = new ViewportLogin();
            viewportLogin.setVisible(true);
        }
    }//GEN-LAST:event_BUTTONSairActionPerformed

    private void BUTTONClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONClientesActionPerformed
        ViewportClients viewportClients = new ViewportClients();
        viewportClients.setVisible(true);
    }//GEN-LAST:event_BUTTONClientesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ViewportsUtils utils = new ViewportsUtils();

        LABELNome.setText(utils.getTwoFirstWords(this.employeeLogged.getName()));
        
        if (!this.employeeLogged.getAcessLevel().equals("Administrador")){
            BUTTONDespesas.setEnabled(false);
            BUTTONDespesas.setText("");
            
            BUTTONFuncionarios.setEnabled(false);
            BUTTONFuncionarios.setText("");
        }
    }//GEN-LAST:event_formWindowActivated

    private void BUTTONDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONDespesasActionPerformed
        if (this.employeeLogged.getAcessLevel().equals("Administrador")) {
            ViewportExpenses viewportExpenses = new ViewportExpenses();
            viewportExpenses.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não possui Acesso...");
        }
    }//GEN-LAST:event_BUTTONDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONClientes;
    private javax.swing.JButton BUTTONDespesas;
    private javax.swing.JButton BUTTONEstoque;
    private javax.swing.JButton BUTTONFuncionarios;
    private javax.swing.JButton BUTTONSair;
    private javax.swing.JButton BUTTONVendas;
    private javax.swing.JLabel LABELNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
