/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import DAOs.StockDAO;
import Models.ProductsModel;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caiol
 */
public class ViewportStock extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportStock.class.getName());

    /**
     * Creates new form ViewportMainMenu
     */
    public ViewportStock() {
        initComponents();
    }

    private void listTable() {
        StockDAO dao = new StockDAO();
        List<ProductsModel> list = dao.listProducts();

        DefaultTableModel tableData = (DefaultTableModel) TableListClients.getModel();
        tableData.setNumRows(0);

        for (ProductsModel c : list) {
            tableData.addRow(new Object[]{
                c.getId(),
                c.getCode(),
                c.getProduct(),
                c.getColor(),
                c.getType(),
                c.getSize(),
                c.getSupplier(),
                c.getPrice(),
                c.getQuantity()
            });
        }
    }

    private void FilteredList() {
        String productCode = "%" + TXTFiltrarCodigo.getText() + "%";
        String productProduct = "%" + TXTFiltrarProduto.getText() + "%";
        String productColor = "%" + TXTFiltrarCor.getText() + "%";
        String productType = "%" + TXTFiltrarTipo.getText() + "%";
        String productSize = "%" + TXTFiltrarTamanho.getText() + "%";
        String productSupplier = "%" + TXTFiltrarFornecedor.getText() + "%";

        StockDAO dao = new StockDAO();
        List<ProductsModel> list = dao.searchProductByFeatures(productProduct,productCode,productColor,productType,productSize,productSupplier);

        DefaultTableModel tableData = (DefaultTableModel) TableListClients.getModel();
        tableData.setNumRows(0);

        for (ProductsModel c : list) {
            tableData.addRow(new Object[]{
                c.getId(),
                c.getCode(),
                c.getProduct(),
                c.getColor(),
                c.getType(),
                c.getSize(),
                c.getPrice(),
                c.getSupplier(),
                c.getQuantity()
            });
        }
    }
    
    private String getProductCode(String productSupplier, String productID, String productProduct, String productType, String productSize, String productColor){
        String productCode = null;
        return productCode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        ClientDataJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTTipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTTamanho = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTQuantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXTCor = new javax.swing.JTextField();
        PesquisarButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TXTCodigoProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTPreco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTFornecedor = new javax.swing.JTextField();
        ConsultJPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TXTFiltrarCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListClients = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        TXTFiltrarProduto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TXTFiltrarCor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TXTFiltrarTipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TXTFiltrarTamanho = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TXTFiltrarFornecedor = new javax.swing.JTextField();
        EDITARButton = new javax.swing.JButton();
        EXCLUIRButton = new javax.swing.JButton();
        NOVOButton = new javax.swing.JButton();

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));
        jPanel1.setForeground(new java.awt.Color(192, 179, 166));

        jPanel2.setBackground(new java.awt.Color(149, 117, 47));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        MainTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        MainTabbedPane.setForeground(new java.awt.Color(0, 0, 0));

        ClientDataJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ClientDataJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClientDataJPanel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código:");

        TXTCodigo.setEditable(false);
        TXTCodigo.setBackground(new java.awt.Color(204, 204, 204));
        TXTCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCodigo.setForeground(new java.awt.Color(0, 0, 0));
        TXTCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCodigo.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Produto:");

        TXTProduto.setBackground(new java.awt.Color(255, 255, 255));
        TXTProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTProduto.setForeground(new java.awt.Color(0, 0, 0));
        TXTProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo:");

        TXTTipo.setBackground(new java.awt.Color(255, 255, 255));
        TXTTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTTipo.setForeground(new java.awt.Color(0, 0, 0));
        TXTTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTipoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tamanho:");

        TXTTamanho.setBackground(new java.awt.Color(255, 255, 255));
        TXTTamanho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTTamanho.setForeground(new java.awt.Color(0, 0, 0));
        TXTTamanho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTamanhoActionPerformed(evt);
            }
        });
        TXTTamanho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTTamanhoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantidade:");

        TXTQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        TXTQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        TXTQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cor:");

        TXTCor.setBackground(new java.awt.Color(255, 255, 255));
        TXTCor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCor.setForeground(new java.awt.Color(0, 0, 0));
        TXTCor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PesquisarButton.setBackground(new java.awt.Color(192, 179, 166));
        PesquisarButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        PesquisarButton.setForeground(new java.awt.Color(0, 0, 0));
        PesquisarButton.setText("Pesquisar");
        PesquisarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Código de Produto:");

        TXTCodigoProduto.setBackground(new java.awt.Color(255, 255, 255));
        TXTCodigoProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTCodigoProduto.setForeground(new java.awt.Color(0, 0, 0));
        TXTCodigoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCodigoProduto.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Preço:");

        TXTPreco.setBackground(new java.awt.Color(255, 255, 255));
        TXTPreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTPreco.setForeground(new java.awt.Color(0, 0, 0));
        TXTPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPrecoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fornecedor:");

        TXTFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        TXTFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        TXTFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClientDataJPanelLayout = new javax.swing.GroupLayout(ClientDataJPanel);
        ClientDataJPanel.setLayout(ClientDataJPanelLayout);
        ClientDataJPanelLayout.setHorizontalGroup(
            ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TXTCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientDataJPanelLayout.createSequentialGroup()
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TXTTamanho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientDataJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientDataJPanelLayout.createSequentialGroup()
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(TXTCor))))
                        .addGap(168, 168, 168))))
        );
        ClientDataJPanelLayout.setVerticalGroup(
            ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientDataJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TXTCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TXTTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ClientDataJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TXTFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        MainTabbedPane.addTab("Dados Pessoais", ClientDataJPanel);

        ConsultJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ConsultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Codigo:");

        TXTFiltrarCodigo.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarCodigo.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarCodigoKeyPressed(evt);
            }
        });

        TableListClients.setBackground(new java.awt.Color(233, 220, 205));
        TableListClients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableListClients.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableListClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Produto", "Cor", "Tipo", "Tamanho", "Fornecedor", "Preço", "Quantidade"
            }
        ));
        TableListClients.setGridColor(new java.awt.Color(255, 255, 255));
        TableListClients.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TableListClients.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TableListClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableListClients);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Produto:");

        TXTFiltrarProduto.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarProduto.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarProdutoKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cor:");

        TXTFiltrarCor.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarCor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarCor.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarCor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarCorKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Tipo:");

        TXTFiltrarTipo.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarTipo.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarTipoKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tamanho:");

        TXTFiltrarTamanho.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarTamanho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarTamanho.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarTamanho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarTamanho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarTamanhoKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fornecedor");

        TXTFiltrarFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        TXTFiltrarFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTFiltrarFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        TXTFiltrarFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTFiltrarFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTFiltrarFornecedorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ConsultJPanelLayout = new javax.swing.GroupLayout(ConsultJPanel);
        ConsultJPanel.setLayout(ConsultJPanelLayout);
        ConsultJPanelLayout.setHorizontalGroup(
            ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(ConsultJPanelLayout.createSequentialGroup()
                        .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTFiltrarTipo)
                            .addComponent(TXTFiltrarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultJPanelLayout.createSequentialGroup()
                                .addComponent(TXTFiltrarTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(ConsultJPanelLayout.createSequentialGroup()
                                .addComponent(TXTFiltrarProduto)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTFiltrarCor)
                            .addComponent(TXTFiltrarFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                        .addGap(47, 47, 47))))
        );
        ConsultJPanelLayout.setVerticalGroup(
            ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXTFiltrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(TXTFiltrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(TXTFiltrarCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TXTFiltrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TXTFiltrarTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TXTFiltrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Consultar", ConsultJPanel);

        EDITARButton.setBackground(new java.awt.Color(255, 255, 255));
        EDITARButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EDITARButton.setForeground(new java.awt.Color(0, 0, 0));
        EDITARButton.setText("EDITAR");
        EDITARButton.setToolTipText("");
        EDITARButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EDITARButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARButtonActionPerformed(evt);
            }
        });

        EXCLUIRButton.setBackground(new java.awt.Color(255, 255, 255));
        EXCLUIRButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EXCLUIRButton.setForeground(new java.awt.Color(0, 0, 0));
        EXCLUIRButton.setText("EXCLUIR");
        EXCLUIRButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EXCLUIRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIRButtonActionPerformed(evt);
            }
        });

        NOVOButton.setBackground(new java.awt.Color(255, 255, 255));
        NOVOButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NOVOButton.setForeground(new java.awt.Color(0, 0, 0));
        NOVOButton.setText("NOVO");
        NOVOButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NOVOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOVOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainTabbedPane)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NOVOButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EDITARButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EXCLUIRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDITARButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXCLUIRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOVOButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTipoActionPerformed

    private void TXTTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTamanhoActionPerformed

    private void TXTProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTProdutoActionPerformed

    private void EDITARButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARButtonActionPerformed
        if (TXTProduto.getText() != null && TXTPreco.getText() != null) {
            try {
                ProductsModel currentProduct = new ProductsModel();

                currentProduct.setId(Integer.parseInt(TXTCodigo.getText()));
                //currentProduct.setCode(getProductCode());
                currentProduct.setProduct(TXTProduto.getText());
                currentProduct.setColor(TXTCor.getText());
                currentProduct.setType(TXTTipo.getText());
                currentProduct.setSize(TXTTamanho.getText());
                currentProduct.setPrice(Double.parseDouble(TXTPreco.getText()));
                currentProduct.setQuantity(Integer.parseInt(TXTQuantidade.getText()));
                currentProduct.setSupplier(TXTFornecedor.getText());

                StockDAO dao = new StockDAO();

                dao.updateProduct(currentProduct);

            } catch (Exception e) {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Produto e/ou Preco inválidos.");
        }
    }//GEN-LAST:event_EDITARButtonActionPerformed

    private void EXCLUIRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIRButtonActionPerformed
        if (TXTProduto.getText() != null && TXTCor.getText() != null) {
            try {
                ProductsModel currentProduct = new ProductsModel();

                currentProduct.setId(Integer.parseInt(TXTCodigo.getText()));

                StockDAO dao = new StockDAO();

                dao.deleteProduct(currentProduct);

                new ViewportsUtils().clearPanel(ClientDataJPanel);
            } catch (Exception e) {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Nome e/ou um CPF válidos.");
        }
    }//GEN-LAST:event_EXCLUIRButtonActionPerformed

    private void NOVOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOVOButtonActionPerformed
        if (TXTProduto.getText() != null && TXTPreco.getText() != null) {
            try {
                ProductsModel currentProduct = new ProductsModel();
                
                //currentProduct.setCode(getProductCode());
                currentProduct.setProduct(TXTProduto.getText());
                currentProduct.setColor(TXTCor.getText());
                currentProduct.setType(TXTPreco.getText());
                currentProduct.setSize(TXTTamanho.getText());
                currentProduct.setPrice(Double.parseDouble(TXTPreco.getText()));
                currentProduct.setQuantity(Integer.parseInt(TXTQuantidade.getText()));
                currentProduct.setSupplier(TXTFornecedor.getText());

                StockDAO dao = new StockDAO();

                dao.registerProduct(currentProduct);

                new ViewportsUtils().clearPanel(ClientDataJPanel);
            } catch (Exception e) {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Nome e/ou um CPF válidos.");
        }
    }//GEN-LAST:event_NOVOButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTable();
    }//GEN-LAST:event_formWindowActivated

    private void TableListClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListClientsMouseClicked
        TXTCodigo.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 0).toString());
        TXTProduto.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 1).toString());
        TXTCor.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 2).toString());
        TXTTipo.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 4).toString());
        TXTTamanho.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 5).toString());
        TXTQuantidade.setText(TableListClients.getValueAt(TableListClients.getSelectedRow(), 6).toString());

        MainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_TableListClientsMouseClicked

    private void TXTFiltrarCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarCodigoKeyPressed
        FilteredList();
    }//GEN-LAST:event_TXTFiltrarCodigoKeyPressed

    private void PesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarButtonActionPerformed
        String productCode = TXTCodigoProduto.getText();
        ProductsModel product = new ProductsModel();
        StockDAO dao = new StockDAO();

        product = dao.consultProductByCode(productCode);

        if (product.getProduct() != null) {
            TXTCodigo.setText(String.valueOf(product.getId()));
            TXTProduto.setText(product.getProduct());
            TXTCor.setText(product.getColor());
            TXTTipo.setText(product.getType());
            TXTTamanho.setText(product.getSize());
            TXTQuantidade.setText(String.valueOf(product.getQuantity()));
        } else {
            JOptionPane.showMessageDialog(null, "FALHA ao ENCONTRAR Cliente de codigo: " + productCode);
        }
    }//GEN-LAST:event_PesquisarButtonActionPerformed

    private void TXTTamanhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTTamanhoKeyPressed

    }//GEN-LAST:event_TXTTamanhoKeyPressed

    private void TXTPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPrecoActionPerformed

    private void TXTFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFornecedorActionPerformed

    private void TXTFiltrarProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarProdutoKeyPressed
        FilteredList();
    }//GEN-LAST:event_TXTFiltrarProdutoKeyPressed

    private void TXTFiltrarCorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarCorKeyPressed
        FilteredList();
    }//GEN-LAST:event_TXTFiltrarCorKeyPressed

    private void TXTFiltrarTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarTipoKeyPressed
        FilteredList();
    }//GEN-LAST:event_TXTFiltrarTipoKeyPressed

    private void TXTFiltrarTamanhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarTamanhoKeyPressed
        FilteredList();
    }//GEN-LAST:event_TXTFiltrarTamanhoKeyPressed

    private void TXTFiltrarFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarFornecedorKeyPressed
        FilteredList();
    }//GEN-LAST:event_TXTFiltrarFornecedorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewportStock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientDataJPanel;
    private javax.swing.JPanel ConsultJPanel;
    private javax.swing.JButton EDITARButton;
    private javax.swing.JButton EXCLUIRButton;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton NOVOButton;
    private javax.swing.JButton PesquisarButton;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JTextField TXTCodigoProduto;
    private javax.swing.JTextField TXTCor;
    private javax.swing.JTextField TXTFiltrarCodigo;
    private javax.swing.JTextField TXTFiltrarCor;
    private javax.swing.JTextField TXTFiltrarFornecedor;
    private javax.swing.JTextField TXTFiltrarProduto;
    private javax.swing.JTextField TXTFiltrarTamanho;
    private javax.swing.JTextField TXTFiltrarTipo;
    private javax.swing.JTextField TXTFornecedor;
    private javax.swing.JTextField TXTPreco;
    private javax.swing.JTextField TXTProduto;
    private javax.swing.JTextField TXTQuantidade;
    private javax.swing.JTextField TXTTamanho;
    private javax.swing.JTextField TXTTipo;
    private javax.swing.JTable TableListClients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
