/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import Models.AddressModel;
import Models.CashFilterDocument;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author caiol
 */
public class ViewportPayments extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportPayments.class.getName());

    private double totalPrice;
    private double totalPaid = 0, totalInCash = 0; 
    private double minimumInstallmentsValue = 30.00;
    
    // SALE DATA:
    public String client_name;
    public String client_cpf;
    public String date;
    public DefaultTableModel cart;

    /**
     * Creates new form ViewportPagamentos
     * @param totalPrice
     * @param client_name
     * @param client_cpf
     * @param date
     * @param cart
     */
    public ViewportPayments(
            double totalPrice,
            String client_name,
            String client_cpf,
            String date,
            DefaultTableModel cart
        ) 
    {
        initComponents();
        this.totalPrice = totalPrice;
        this.client_name = client_name;
        this.client_cpf = client_cpf;
        this.date = date;
        this.cart = cart;
        
        ((AbstractDocument) TXTDinheiro.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTDebito.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTPIX.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTCredito.getDocument()).setDocumentFilter(new CashFilterDocument());
        ((AbstractDocument) TXTLink.getDocument()).setDocumentFilter(new CashFilterDocument());
    }

    private ArrayList<String> CalculateInstallments() {
        ArrayList<String> plots = new ArrayList<>();

        for (int i = 1; i <= 12; i++) {
            if (Double.parseDouble(TXTCredito.getText().replace(",", ".")) / i >= minimumInstallmentsValue) {
                plots.add(i + "x");
            } else {
                if (plots.isEmpty()) {
                    plots.add("1x");
                }
                break;
            }
        }

        return plots;
    }

    private void UpdateCBParcelas() {
        ArrayList<String> installmentsList = new ArrayList<>();

        DefaultComboBoxModel model = (DefaultComboBoxModel) CBParcelas.getModel();
        model.removeAllElements();
        
        if (!TXTCredito.getText().isBlank()) {
            if (Double.parseDouble(TXTCredito.getText()) > 0) {
                installmentsList = CalculateInstallments();
            }
            else {
                installmentsList.add("1x");
            }
        }
        else {
            installmentsList.add("1x");
        }

        for (String plot : installmentsList) {
            model.addElement(plot);
        }
    }
    
    private void UpdateSelectedIndex(int nextSelectedIndex){
        int previousSelectedIndex = TABBEDPANEMain.getSelectedIndex();
        TABBEDPANEMain.setSelectedIndex(nextSelectedIndex);
        
        TABBEDPANEMain.setEnabledAt(previousSelectedIndex, false);
        TABBEDPANEMain.setBackgroundAt(previousSelectedIndex, new Color(204, 204, 204));
        
        TABBEDPANEMain.setEnabledAt(nextSelectedIndex, true);
        TABBEDPANEMain.setBackgroundAt(nextSelectedIndex, new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LABELTotalVenda = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TABBEDPANEMain = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        BTNCancelarDinheiro = new javax.swing.JButton();
        BTNConfirmarDinheiro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTDinheiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LABELTotalDinheiro = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BTNConfirmarDebito = new javax.swing.JButton();
        BTNCancelarDebito = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LABELTotalDebito = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TXTDebito = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        BTNConfirmarPIX = new javax.swing.JButton();
        BTNCancelarPIX = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LABELTotalPIX = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TXTPIX = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        BTNConfirmarLink = new javax.swing.JButton();
        BTNCancelarBoleto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LABELTotalLink = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TXTLink = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        BTNConfirmarCredito = new javax.swing.JButton();
        BTNCancelarCredito = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        LABELTotalCredito = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TXTCredito = new javax.swing.JTextField();
        CBParcelas = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TXTCEP = new javax.swing.JTextField();
        TXTEndereco = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TXTTelefone = new javax.swing.JTextField();
        BUTTONPreencher = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        TXTNumero = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TXTReferencia = new javax.swing.JTextField();
        BTNConfirmarFinalizar = new javax.swing.JButton();
        BTNCancelarFinalizar = new javax.swing.JButton();
        CHECKDesconto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));

        jPanel2.setBackground(new java.awt.Color(149, 117, 47));

        LABELTotalVenda.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalVenda.setForeground(new java.awt.Color(0, 0, 0));
        LABELTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalVenda.setText("0.00");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("TOTAL DA VENDA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalVenda)
                .addContainerGap())
        );

        TABBEDPANEMain.setBackground(new java.awt.Color(255, 255, 255));
        TABBEDPANEMain.setForeground(new java.awt.Color(0, 0, 0));
        TABBEDPANEMain.setEnabled(false);
        TABBEDPANEMain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BTNCancelarDinheiro.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarDinheiro.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarDinheiro.setText("CANCELAR");
        BTNCancelarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarDinheiroActionPerformed(evt);
            }
        });

        BTNConfirmarDinheiro.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarDinheiro.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarDinheiro.setText("CONFIRMAR");
        BTNConfirmarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarDinheiroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dinheiro:");

        TXTDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        TXTDinheiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTDinheiro.setForeground(new java.awt.Color(0, 0, 0));
        TXTDinheiro.setText("0.00");
        TXTDinheiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTDinheiroKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL A PAGAR:");

        LABELTotalDinheiro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalDinheiro.setForeground(new java.awt.Color(204, 0, 0));
        LABELTotalDinheiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalDinheiro.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTDinheiro))
                            .addComponent(BTNConfirmarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(BTNCancelarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LABELTotalDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalDinheiro)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BTNConfirmarDinheiro, jLabel1});

        TABBEDPANEMain.addTab("Dinheiro", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        BTNConfirmarDebito.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarDebito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarDebito.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarDebito.setText("CONFIRMAR");
        BTNConfirmarDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarDebitoActionPerformed(evt);
            }
        });

        BTNCancelarDebito.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarDebito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarDebito.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarDebito.setText("CANCELAR");
        BTNCancelarDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarDebitoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TOTAL A PAGAR:");

        LABELTotalDebito.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalDebito.setForeground(new java.awt.Color(204, 0, 0));
        LABELTotalDebito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalDebito.setText("0.00");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Débito:");

        TXTDebito.setBackground(new java.awt.Color(255, 255, 255));
        TXTDebito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTDebito.setForeground(new java.awt.Color(0, 0, 0));
        TXTDebito.setText("0.00");
        TXTDebito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalDebito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTDebito))
                            .addComponent(BTNConfirmarDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(BTNCancelarDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalDebito)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TABBEDPANEMain.addTab("Débito", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        BTNConfirmarPIX.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarPIX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarPIX.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarPIX.setText("CONFIRMAR");
        BTNConfirmarPIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarPIXActionPerformed(evt);
            }
        });

        BTNCancelarPIX.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarPIX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarPIX.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarPIX.setText("CANCELAR");
        BTNCancelarPIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarPIXActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOTAL A PAGAR:");

        LABELTotalPIX.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalPIX.setForeground(new java.awt.Color(204, 0, 0));
        LABELTotalPIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalPIX.setText("0.00");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("PIX:");

        TXTPIX.setBackground(new java.awt.Color(255, 255, 255));
        TXTPIX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTPIX.setForeground(new java.awt.Color(0, 0, 0));
        TXTPIX.setText("0.00");
        TXTPIX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalPIX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTPIX))
                            .addComponent(BTNConfirmarPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(BTNCancelarPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalPIX)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TABBEDPANEMain.addTab("PIX", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        BTNConfirmarLink.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarLink.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarLink.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarLink.setText("CONFIRMAR");
        BTNConfirmarLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarLinkActionPerformed(evt);
            }
        });

        BTNCancelarBoleto.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarBoleto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarBoleto.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarBoleto.setText("CANCELAR");
        BTNCancelarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarBoletoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TOTAL A PAGAR:");

        LABELTotalLink.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalLink.setForeground(new java.awt.Color(204, 0, 0));
        LABELTotalLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalLink.setText("0.00");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Valor:");

        TXTLink.setBackground(new java.awt.Color(255, 255, 255));
        TXTLink.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTLink.setForeground(new java.awt.Color(0, 0, 0));
        TXTLink.setText("0.00");
        TXTLink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTLink))
                            .addComponent(BTNConfirmarLink, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(BTNCancelarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalLink)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTLink, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarLink, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TABBEDPANEMain.addTab("Link de Pagamento", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        BTNConfirmarCredito.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarCredito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarCredito.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarCredito.setText("CONFIRMAR");
        BTNConfirmarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarCreditoActionPerformed(evt);
            }
        });

        BTNCancelarCredito.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarCredito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarCredito.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarCredito.setText("CANCELAR");
        BTNCancelarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarCreditoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TOTAL A PAGAR:");

        LABELTotalCredito.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LABELTotalCredito.setForeground(new java.awt.Color(204, 0, 0));
        LABELTotalCredito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalCredito.setText("0.00");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Crédito:");

        TXTCredito.setBackground(new java.awt.Color(255, 255, 255));
        TXTCredito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTCredito.setForeground(new java.awt.Color(0, 0, 0));
        TXTCredito.setText("0.00");
        TXTCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCreditoKeyTyped(evt);
            }
        });

        CBParcelas.setBackground(new java.awt.Color(255, 255, 255));
        CBParcelas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBParcelas.setForeground(new java.awt.Color(0, 0, 0));
        CBParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x", "2x", "3x", "4x", "5x", "6x", "7x", "8x", "9x", "10x", "11x", "12x" }));
        CBParcelas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CBParcelasPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 89, Short.MAX_VALUE)
                        .addComponent(CBParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(BTNConfirmarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNCancelarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalCredito)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TABBEDPANEMain.addTab("Crédito", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaminhaoPreto.png"))); // NOI18N
        jLabel26.setText("(Opcional) Endereço para entrega");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("CEP:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Endereço:");

        TXTCEP.setBackground(new java.awt.Color(255, 255, 255));
        TXTCEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTCEP.setForeground(new java.awt.Color(0, 0, 0));
        TXTCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TXTEndereco.setBackground(new java.awt.Color(255, 255, 255));
        TXTEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTEndereco.setForeground(new java.awt.Color(0, 0, 0));
        TXTEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Telefone para Contato:");

        TXTTelefone.setBackground(new java.awt.Color(255, 255, 255));
        TXTTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTTelefone.setForeground(new java.awt.Color(0, 0, 0));
        TXTTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BUTTONPreencher.setBackground(new java.awt.Color(192, 179, 166));
        BUTTONPreencher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTONPreencher.setForeground(new java.awt.Color(0, 0, 102));
        BUTTONPreencher.setText("Preencher");
        BUTTONPreencher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONPreencherActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Número:");

        TXTNumero.setBackground(new java.awt.Color(255, 255, 255));
        TXTNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTNumero.setForeground(new java.awt.Color(0, 0, 0));
        TXTNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Referência:");

        TXTReferencia.setBackground(new java.awt.Color(255, 255, 255));
        TXTReferencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTReferencia.setForeground(new java.awt.Color(0, 0, 0));
        TXTReferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTEndereco)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(TXTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BUTTONPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(TXTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(TXTTelefone))))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BTNConfirmarFinalizar.setBackground(new java.awt.Color(149, 117, 47));
        BTNConfirmarFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNConfirmarFinalizar.setForeground(new java.awt.Color(0, 0, 153));
        BTNConfirmarFinalizar.setText("CONFIRMAR");
        BTNConfirmarFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfirmarFinalizarActionPerformed(evt);
            }
        });

        BTNCancelarFinalizar.setBackground(new java.awt.Color(149, 117, 47));
        BTNCancelarFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNCancelarFinalizar.setForeground(new java.awt.Color(153, 0, 0));
        BTNCancelarFinalizar.setText("CANCELAR");
        BTNCancelarFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarFinalizarActionPerformed(evt);
            }
        });

        CHECKDesconto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CHECKDesconto.setForeground(new java.awt.Color(153, 0, 0));
        CHECKDesconto.setText("Deconto de 5% (Pix e Dinheiro)");
        CHECKDesconto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHECKDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(BTNConfirmarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNCancelarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CHECKDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(CHECKDesconto)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConfirmarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCancelarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TABBEDPANEMain.addTab("FINALIZAR", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TABBEDPANEMain)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TABBEDPANEMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        LABELTotalVenda.setText(String.valueOf(this.totalPrice));
        
        LABELTotalDinheiro.setText(String.valueOf(this.totalPrice));
        
        UpdateSelectedIndex(0);
    }//GEN-LAST:event_formWindowActivated

    private void CBParcelasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CBParcelasPropertyChange

    }//GEN-LAST:event_CBParcelasPropertyChange

    private void BUTTONPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONPreencherActionPerformed
        AddressModel c = new AddressModel();
        ViewportsUtils utils = new ViewportsUtils();

        c = utils.fillAddressByCep(TXTCEP.getText());

        TXTEndereco.setText(c.getAddress());
    }//GEN-LAST:event_BUTTONPreencherActionPerformed

    private void BTNConfirmarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarDinheiroActionPerformed
        totalPaid += Double.parseDouble(TXTDinheiro.getText());
        totalInCash += Double.parseDouble(TXTDinheiro.getText());
        
        if(totalPrice - totalPaid > 0){
            LABELTotalDebito.setText(String.valueOf(totalPrice - totalPaid));
        
            UpdateSelectedIndex(1);
        }
        else{
            UpdateSelectedIndex(5);
        }
    }//GEN-LAST:event_BTNConfirmarDinheiroActionPerformed

    private void BTNConfirmarDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarDebitoActionPerformed
        totalPaid += Double.parseDouble(TXTDebito.getText());
        
        if(totalPrice - totalPaid > 0){
            LABELTotalPIX.setText(String.valueOf(totalPrice - totalPaid));
        
            UpdateSelectedIndex(2);
        }
        else{
            UpdateSelectedIndex(5);
        }
    }//GEN-LAST:event_BTNConfirmarDebitoActionPerformed

    private void BTNConfirmarPIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarPIXActionPerformed
        totalPaid += Double.parseDouble(TXTPIX.getText());
        totalInCash += Double.parseDouble(TXTPIX.getText());
        
        if(totalPrice - totalPaid > 0){
            LABELTotalLink.setText(String.valueOf(totalPrice - totalPaid));
        
            UpdateSelectedIndex(3);
        }
        else{
            UpdateSelectedIndex(5);
        }
    }//GEN-LAST:event_BTNConfirmarPIXActionPerformed

    private void BTNConfirmarLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarLinkActionPerformed
        totalPaid += Double.parseDouble(TXTLink.getText());
        
        if(totalPrice - totalPaid > 0){
            LABELTotalCredito.setText(String.valueOf(totalPrice - totalPaid));
        
            UpdateSelectedIndex(4);
        }
        else{
            UpdateSelectedIndex(5);
        }
    }//GEN-LAST:event_BTNConfirmarLinkActionPerformed

    private void BTNConfirmarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarCreditoActionPerformed
        totalPaid += Double.parseDouble(TXTCredito.getText());
        
        UpdateSelectedIndex(5);
    }//GEN-LAST:event_BTNConfirmarCreditoActionPerformed

    private void BTNCancelarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarDinheiroActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarDinheiroActionPerformed

    private void BTNCancelarDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarDebitoActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarDebitoActionPerformed

    private void BTNCancelarPIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarPIXActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarPIXActionPerformed

    private void BTNCancelarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarBoletoActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarBoletoActionPerformed

    private void BTNCancelarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarCreditoActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarCreditoActionPerformed

    private void BTNConfirmarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfirmarFinalizarActionPerformed
        if (totalPaid >= totalPrice){
            double totalPrice = this.totalPrice;
            double totalPaid = this.totalPaid;
            double totalInCash = this.totalInCash;
            boolean isDiscount = CHECKDesconto.isSelected();
            String client_name = this.client_name;
            String client_cpf = this.client_cpf;
            String date = this.date;
            double cash = Double.parseDouble(TXTDinheiro.getText());
            double debit = Double.parseDouble(TXTDebito.getText());
            double pix = Double.parseDouble(TXTPIX.getText());
            double link = Double.parseDouble(TXTLink.getText());
            double credit = Double.parseDouble(TXTCredito.getText());
            int installments = CBParcelas.getSelectedIndex() + 1;
            String client_address = TXTEndereco.getText() + ", " + TXTNumero.getText() + ", " + TXTCEP.getText();
            String client_address_ref = TXTReferencia.getText();
            DefaultTableModel cart = this.cart;
            
            ViewportConfirmSale viewCS = new ViewportConfirmSale(totalPrice, totalPaid, totalInCash, isDiscount, client_name, client_cpf, date, cash, debit, pix, link, credit, installments, client_address, client_address_ref, cart);

            viewCS.setVisible(true);
        }
        else{
            totalPaid = 0;
            totalInCash = 0;
            JOptionPane.showMessageDialog(null, "Não pagou todo o valor da compra!");
            UpdateSelectedIndex(0);
        }
    }//GEN-LAST:event_BTNConfirmarFinalizarActionPerformed

    private void BTNCancelarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarFinalizarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNCancelarFinalizarActionPerformed

    private void TXTCreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCreditoKeyTyped
        UpdateCBParcelas();
    }//GEN-LAST:event_TXTCreditoKeyTyped

    private void CHECKDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHECKDescontoActionPerformed

    private void TXTDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDinheiroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDinheiroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Ninbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ViewportPayments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancelarBoleto;
    private javax.swing.JButton BTNCancelarCredito;
    private javax.swing.JButton BTNCancelarDebito;
    private javax.swing.JButton BTNCancelarDinheiro;
    private javax.swing.JButton BTNCancelarFinalizar;
    private javax.swing.JButton BTNCancelarPIX;
    private javax.swing.JButton BTNConfirmarCredito;
    private javax.swing.JButton BTNConfirmarDebito;
    private javax.swing.JButton BTNConfirmarDinheiro;
    private javax.swing.JButton BTNConfirmarFinalizar;
    private javax.swing.JButton BTNConfirmarLink;
    private javax.swing.JButton BTNConfirmarPIX;
    private javax.swing.JButton BUTTONPreencher;
    private javax.swing.JComboBox<String> CBParcelas;
    private javax.swing.JCheckBox CHECKDesconto;
    private javax.swing.JLabel LABELTotalCredito;
    private javax.swing.JLabel LABELTotalDebito;
    private javax.swing.JLabel LABELTotalDinheiro;
    private javax.swing.JLabel LABELTotalLink;
    private javax.swing.JLabel LABELTotalPIX;
    private javax.swing.JLabel LABELTotalVenda;
    private javax.swing.JTabbedPane TABBEDPANEMain;
    private javax.swing.JTextField TXTCEP;
    private javax.swing.JTextField TXTCredito;
    private javax.swing.JTextField TXTDebito;
    private javax.swing.JTextField TXTDinheiro;
    private javax.swing.JTextField TXTEndereco;
    private javax.swing.JTextField TXTLink;
    private javax.swing.JTextField TXTNumero;
    private javax.swing.JTextField TXTPIX;
    private javax.swing.JTextField TXTReferencia;
    private javax.swing.JTextField TXTTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
