/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import DAOs.SalesDAO;
import Models.ItensSalesModel;
import Models.ProductsModel;
import Models.SalesModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caiol
 */
public class ViewportConfirmSale extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportConfirmSale.class.getName());

    private double totalPrice, totalDiscount, totalPaid;
    private int discountAmount = 5;
    
    // SALE DATA:
    public String client_name;
    public String client_cpf;
    public String date;
    public double cash;
    public double debit;
    public double pix;
    public double link;
    public double credit;
    public int installments;
    public String client_address;
    public String client_address_ref;
    public DefaultTableModel cart;
    
    /**
     * Creates new form ViewportConfirmSale
     * @param totalPrice
     * @param totalPaid
     * @param totalInCash
     * @param isDiscount
     * @param client_name
     * @param client_cpf
     * @param date
     * @param cash
     * @param debit
     * @param pix
     * @param link
     * @param credit
     * @param installments
     * @param client_address
     * @param client_address_ref
     * @param cart
     */
    public ViewportConfirmSale (
            double totalPrice,
            double totalPaid,
            double totalInCash,
            boolean isDiscount,
            String client_name,
            String client_cpf,
            String date,
            double cash,
            double debit,
            double pix,
            double link,
            double credit,
            int installments,
            String client_address,
            String client_address_ref,
            DefaultTableModel cart
            ) 
        {
        
        initComponents();
        
        this.totalPrice = totalPrice;
        this.totalPaid = totalPaid;
        this.client_name = client_name;
        this.client_cpf = client_cpf;
        this.date = date;
        this.cash = cash;
        this.debit = debit;
        this.pix = pix;
        this.link = link;
        this.credit = credit;
        this.installments = installments;
        this.client_address = client_address;
        this.client_address_ref = client_address_ref;
        this.cart = cart;
        
        if (isDiscount){
            this.totalDiscount = totalInCash - (totalInCash * (discountAmount / 100)) - totalInCash;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LABELTotalVenda = new javax.swing.JLabel();
        LABELTotalPago = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LABELTroco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTObservacoes = new javax.swing.JTextField();
        BUTTONFinalizar = new javax.swing.JButton();
        LABELTXTTotalComDesconto = new javax.swing.JLabel();
        LABELTotalVendaDesconto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total da Venda:");

        LABELTotalVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABELTotalVenda.setForeground(new java.awt.Color(153, 0, 0));
        LABELTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELTotalVenda.setText("0.00");

        LABELTotalPago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABELTotalPago.setForeground(new java.awt.Color(51, 102, 0));
        LABELTotalPago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LABELTotalPago.setText("0.00");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Total Pago:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Troco:");

        LABELTroco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABELTroco.setForeground(new java.awt.Color(0, 0, 204));
        LABELTroco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LABELTroco.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("(Opcional) Observações:");

        TXTObservacoes.setBackground(new java.awt.Color(255, 255, 255));
        TXTObservacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTObservacoes.setForeground(new java.awt.Color(0, 0, 0));
        TXTObservacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BUTTONFinalizar.setBackground(new java.awt.Color(149, 117, 47));
        BUTTONFinalizar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BUTTONFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        BUTTONFinalizar.setText("FINALIZAR");
        BUTTONFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONFinalizarActionPerformed(evt);
            }
        });

        LABELTXTTotalComDesconto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABELTXTTotalComDesconto.setForeground(new java.awt.Color(0, 0, 0));
        LABELTXTTotalComDesconto.setText("Total com Desconto de 5%:");

        LABELTotalVendaDesconto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABELTotalVendaDesconto.setForeground(new java.awt.Color(102, 102, 0));
        LABELTotalVendaDesconto.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LABELTotalPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(LABELTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTObservacoes)
                    .addComponent(BUTTONFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTXTTotalComDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABELTotalVendaDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LABELTXTTotalComDesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELTotalVendaDesconto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LABELTotalPago))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LABELTroco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BUTTONFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        LABELTotalVenda.setText(String.valueOf(totalPrice));
        
        LABELTotalPago.setText(String.valueOf(totalPaid));
        
        if (this.totalDiscount > 0f){
            LABELTotalVendaDesconto.setText(String.valueOf(totalPrice - totalDiscount));
        }
        else {
            LABELTotalVendaDesconto.setEnabled(false);
            LABELTXTTotalComDesconto.setEnabled(false);
        }
        
        LABELTroco.setText(String.valueOf((totalPrice - totalDiscount) - totalPaid));
    }//GEN-LAST:event_formWindowActivated

    private void BUTTONFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONFinalizarActionPerformed
        SalesModel sale = new SalesModel();
        
        sale.setClient_name(this.client_name);
        sale.setClient_CPF(this.client_cpf);
        sale.setDate(this.date);
        sale.setTotal(this.totalPrice);
        sale.setCash(this.cash);
        sale.setDebit(this.debit);
        sale.setPix(this.pix);
        sale.setLink(this.link);
        sale.setCredit(this.credit);
        sale.setInstallments(this.installments);
        sale.setClient_address(this.client_address);
        sale.setClient_address_ref(this.client_address_ref);
        sale.setObs(TXTObservacoes.getText());
        
        SalesDAO saleDAO = new SalesDAO();
        saleDAO.registerSale(sale);
        
        sale.setID(saleDAO.getLastIDSale());
        
        for (int i = 0; i < cart.getRowCount(); i++){
            ItensSalesModel item = new ItensSalesModel();
            ProductsModel product = new ProductsModel();
            
            product.setId(Integer.parseInt(cart.getValueAt(i, 0).toString()));
            
            item.setSale(sale);
            item.setProduct(product);
            item.setQuantity(Integer.parseInt(cart.getValueAt(i, 2).toString()));
            item.setSubtotal(Double.parseDouble(cart.getValueAt(i, 4).toString()));
        }
    }//GEN-LAST:event_BUTTONFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONFinalizar;
    private javax.swing.JLabel LABELTXTTotalComDesconto;
    private javax.swing.JLabel LABELTotalPago;
    private javax.swing.JLabel LABELTotalVenda;
    private javax.swing.JLabel LABELTotalVendaDesconto;
    private javax.swing.JLabel LABELTroco;
    private javax.swing.JTextField TXTObservacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
