/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewports;

import DAOs.ClientsDAO;
import DAOs.StockDAO;
import Models.ClientsModel;
import Models.NumberFilterDocument;
import Models.ProductsModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author caiol
 */
public class ViewportSales extends javax.swing.JFrame {

    double total, price, subtotal;
    int quantity;

    DefaultTableModel cart;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewportSales.class.getName());

    /**
     * Creates new form ViewportVendas
     */
    public ViewportSales() {
        initComponents();
        
        ((AbstractDocument) TXTCPFCliente.getDocument()).setDocumentFilter(new NumberFilterDocument());
        ((AbstractDocument) TXTID.getDocument()).setDocumentFilter(new NumberFilterDocument());
        ((AbstractDocument) TXTQuantidade.getDocument()).setDocumentFilter(new NumberFilterDocument());
    }

    private boolean CarrinhoIsEmpty(){
        if (TabelaCarrinho.getRowCount() > 0){
            return false;
        }
        else{
            return true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TXTCPFCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BUTTONPreencherCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TXTNomeCliente = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCarrinho = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel9 = new javax.swing.JLabel();
        BUTTONDeletarRow = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTID = new javax.swing.JTextField();
        BUTTONPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TXTProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTCor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTPreco = new javax.swing.JTextField();
        BUTTONAdicionarItem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TXTQuantidade = new javax.swing.JTextField();
        BUTTONStock = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        TXTTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BUTTONPagamento = new javax.swing.JButton();
        BUTTONCancelar = new javax.swing.JButton();
        LABELData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 179, 166));

        jPanel2.setBackground(new java.awt.Color(149, 117, 47));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        TXTCPFCliente.setBackground(new java.awt.Color(255, 255, 255));
        TXTCPFCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTCPFCliente.setForeground(new java.awt.Color(0, 0, 0));
        TXTCPFCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCPFClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CPF:");

        BUTTONPreencherCliente.setBackground(new java.awt.Color(192, 179, 166));
        BUTTONPreencherCliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BUTTONPreencherCliente.setForeground(new java.awt.Color(0, 0, 0));
        BUTTONPreencherCliente.setText("Preencher");
        BUTTONPreencherCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONPreencherCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONPreencherClienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nome:");

        TXTNomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        TXTNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        TXTNomeCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNomeClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUTTONPreencherCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TXTNomeCliente))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONPreencherCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        TabelaCarrinho.setBackground(new java.awt.Color(255, 255, 255));
        TabelaCarrinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabelaCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TabelaCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        TabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Qtd.", "Preço", "Subtotal"
            }
        ));
        TabelaCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCarrinhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCarrinho);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CarrinhoPreto_Vazio.png"))); // NOI18N
        jLabel9.setText("CARRINHO");

        BUTTONDeletarRow.setBackground(new java.awt.Color(192, 179, 166));
        BUTTONDeletarRow.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BUTTONDeletarRow.setForeground(new java.awt.Color(0, 0, 0));
        BUTTONDeletarRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LixoPreto.png"))); // NOI18N
        BUTTONDeletarRow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONDeletarRow.setFocusPainted(false);
        BUTTONDeletarRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONDeletarRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUTTONDeletarRow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUTTONDeletarRow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID do Produto:");

        TXTID.setBackground(new java.awt.Color(255, 255, 255));
        TXTID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTID.setForeground(new java.awt.Color(0, 0, 0));
        TXTID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TXTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDActionPerformed(evt);
            }
        });

        BUTTONPesquisar.setBackground(new java.awt.Color(192, 179, 166));
        BUTTONPesquisar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BUTTONPesquisar.setForeground(new java.awt.Color(0, 0, 102));
        BUTTONPesquisar.setText("Pesquisar");
        BUTTONPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Produto:");

        TXTProduto.setEditable(false);
        TXTProduto.setBackground(new java.awt.Color(204, 204, 204));
        TXTProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTProduto.setForeground(new java.awt.Color(0, 0, 102));
        TXTProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cor:");

        TXTCor.setEditable(false);
        TXTCor.setBackground(new java.awt.Color(204, 204, 204));
        TXTCor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTCor.setForeground(new java.awt.Color(0, 0, 102));
        TXTCor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Preço/uni:");

        TXTPreco.setEditable(false);
        TXTPreco.setBackground(new java.awt.Color(204, 204, 204));
        TXTPreco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTPreco.setForeground(new java.awt.Color(0, 0, 102));
        TXTPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BUTTONAdicionarItem.setBackground(new java.awt.Color(192, 179, 166));
        BUTTONAdicionarItem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BUTTONAdicionarItem.setForeground(new java.awt.Color(0, 0, 0));
        BUTTONAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CarrinhoPreto_Add.png"))); // NOI18N
        BUTTONAdicionarItem.setText("Adicionar Item");
        BUTTONAdicionarItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONAdicionarItem.setFocusPainted(false);
        BUTTONAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONAdicionarItemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Quantidade:");

        TXTQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        TXTQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        TXTQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BUTTONStock.setBackground(new java.awt.Color(149, 117, 47));
        BUTTONStock.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BUTTONStock.setForeground(new java.awt.Color(0, 0, 0));
        BUTTONStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Produtos.png"))); // NOI18N
        BUTTONStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BUTTONStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTTONAdicionarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(BUTTONStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTProduto)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(TXTID, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BUTTONPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(TXTCor)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(TXTQuantidade))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTCor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TXTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTTONStock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TXTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BUTTONAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(149, 117, 47));

        TXTTotal.setEditable(false);
        TXTTotal.setBackground(new java.awt.Color(204, 204, 204));
        TXTTotal.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TXTTotal.setForeground(new java.awt.Color(0, 0, 102));
        TXTTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("TOTAL:");

        BUTTONPagamento.setBackground(new java.awt.Color(149, 117, 47));
        BUTTONPagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BUTTONPagamento.setForeground(new java.awt.Color(0, 0, 0));
        BUTTONPagamento.setText("PAGAMENTO");
        BUTTONPagamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONPagamento.setFocusPainted(false);
        BUTTONPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONPagamentoActionPerformed(evt);
            }
        });

        BUTTONCancelar.setBackground(new java.awt.Color(149, 117, 47));
        BUTTONCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BUTTONCancelar.setForeground(new java.awt.Color(153, 0, 0));
        BUTTONCancelar.setText("CANCELAR");
        BUTTONCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTONCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONCancelarActionPerformed(evt);
            }
        });

        LABELData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABELData.setForeground(new java.awt.Color(0, 0, 0));
        LABELData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELData.setText("DATA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(BUTTONPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BUTTONCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(TXTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LABELData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BUTTONCancelar, BUTTONPagamento});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LABELData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTONPagamento)
                    .addComponent(BUTTONCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BUTTONCancelar, BUTTONPagamento});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTONAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONAdicionarItemActionPerformed
        if (!TXTQuantidade.getText().isBlank() && Integer.parseInt(TXTQuantidade.getText()) > 0) {
            this.quantity = Integer.parseInt(TXTQuantidade.getText());
            this.price = Double.parseDouble(TXTPreco.getText());

            this.subtotal = this.quantity * this.price;

            this.cart = (DefaultTableModel) TabelaCarrinho.getModel();

            int productCartPos = getProductPosInCart(Integer.parseInt(TXTID.getText()));

            if (productCartPos >= 0){
                int inCartQuantity = Integer.parseInt(cart.getValueAt(productCartPos, 2).toString());
                double inCartSubtotal = Double.parseDouble(cart.getValueAt(productCartPos, 4).toString());
                
                this.quantity += inCartQuantity;
                this.subtotal = this.quantity * this.price;
                
                this.total -= inCartSubtotal;
            }
            
            StockDAO stockDAO = new StockDAO();
            
            if ( stockDAO.getProductStock(Integer.parseInt(TXTID.getText()) ) >= this.quantity){
                if (productCartPos >= 0){
                    cart.setValueAt(this.quantity, productCartPos, 2);
                    cart.setValueAt(this.subtotal, productCartPos, 4);
                }
                else{
                    this.cart.addRow(new Object[]{
                    TXTID.getText(),
                    TXTProduto.getText(),
                    this.quantity,
                    this.price,
                    this.subtotal 
                    });
                }
                
                this.total += this.subtotal;
                TXTTotal.setText(String.valueOf(this.total));
            }
            else {
                JOptionPane.showMessageDialog(null, "ERRO: Não há quantidade suficiente deste produto em Estoque.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "ERRO: Insira uma quantidade do produto");
        }
    }//GEN-LAST:event_BUTTONAdicionarItemActionPerformed

    private int getProductPosInCart(int productID){
        for (int i = 0; i < this.cart.getRowCount(); i++) {
            int rowProductID = Integer.parseInt(cart.getValueAt(i, 0).toString());
            
            if (rowProductID == productID){
                return i;
            }
        }
        
        return -1;
    }
    
    private void TXTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDActionPerformed

    private void TXTCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCPFClienteActionPerformed

    private void TXTNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNomeClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date date = new Date();

        SimpleDateFormat dateBR = new SimpleDateFormat("dd/MM/yyyy");
        String dateFormated = dateBR.format(date);

        LABELData.setText(dateFormated);
    }//GEN-LAST:event_formWindowActivated

    private void BUTTONPreencherClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONPreencherClienteActionPerformed
        String clientCPF = TXTCPFCliente.getText();
        ClientsModel client = new ClientsModel();
        ClientsDAO dao = new ClientsDAO();

        client = dao.consultClientByCPF(clientCPF);

        if (client.getName() != null) {
            TXTNomeCliente.setText(client.getName());
        } else {
            JOptionPane.showMessageDialog(null, "FALHA ao ENCONTRAR Cliente de CPF: " + clientCPF);
        }
    }//GEN-LAST:event_BUTTONPreencherClienteActionPerformed

    private void BUTTONPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONPesquisarActionPerformed
        int productID = Integer.parseInt(TXTID.getText());
        ProductsModel product = new ProductsModel();
        StockDAO dao = new StockDAO();

        product = dao.consultProductByID(productID);

        if (product.getProduct() != null) {
            TXTProduto.setText(product.getProduct());
            TXTCor.setText(product.getColor());
            TXTPreco.setText(String.valueOf(product.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "FALHA ao ENCONTRAR Produto de ID: " + productID);
        }
    }//GEN-LAST:event_BUTTONPesquisarActionPerformed

    private void BUTTONStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONStockActionPerformed
        ViewportStock viewS = new ViewportStock();
        viewS.MainTabbedPane.setSelectedIndex(1);

        viewS.setVisible(true);
    }//GEN-LAST:event_BUTTONStockActionPerformed

    private void BUTTONPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONPagamentoActionPerformed
        if (TabelaCarrinho.getRowCount() > 0){
            Date date = new Date();
            SimpleDateFormat dateEUA = new SimpleDateFormat("yyyy-MM-dd");
            String dateFormated = dateEUA.format(date);
            
            ViewportPayments viewP = new ViewportPayments(Double.parseDouble(TXTTotal.getText()), TXTNomeCliente.getText(), TXTCPFCliente.getText(), dateFormated, this.cart);
            
            viewP.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Sem produtos no Carrinho");
        }
    }//GEN-LAST:event_BUTTONPagamentoActionPerformed

    private void BUTTONDeletarRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONDeletarRowActionPerformed
        if(TabelaCarrinho.getSelectedRowCount() == 1 && !CarrinhoIsEmpty()){
            DefaultTableModel model = (DefaultTableModel) TabelaCarrinho.getModel();
            
            this.total -= Double.parseDouble(TabelaCarrinho.getValueAt(TabelaCarrinho.getSelectedRow(), 4).toString());
            
            TXTTotal.setText(String.valueOf(this.total));
            
            model.removeRow(TabelaCarrinho.getSelectedRow());
        }
    }//GEN-LAST:event_BUTTONDeletarRowActionPerformed

    private void TabelaCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCarrinhoMouseClicked
        
    }//GEN-LAST:event_TabelaCarrinhoMouseClicked

    private void BUTTONCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Ninbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewportSales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONAdicionarItem;
    private javax.swing.JButton BUTTONCancelar;
    private javax.swing.JButton BUTTONDeletarRow;
    private javax.swing.JButton BUTTONPagamento;
    private javax.swing.JButton BUTTONPesquisar;
    private javax.swing.JButton BUTTONPreencherCliente;
    private javax.swing.JButton BUTTONStock;
    private javax.swing.JLabel LABELData;
    private javax.swing.JTextField TXTCPFCliente;
    private javax.swing.JTextField TXTCor;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTNomeCliente;
    private javax.swing.JTextField TXTPreco;
    private javax.swing.JTextField TXTProduto;
    private javax.swing.JTextField TXTQuantidade;
    private javax.swing.JTextField TXTTotal;
    private javax.swing.JTable TabelaCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
